### ISSUE TITLE
DataBase_Impl does not exist

### ISSUE THREAD

**Issue by Anu07** [ritesh-singh/WeatherApplication#2]
Error:cannot find implementation for com.application.room.UserDataBase.

Hi,I have followed your tutorial.But getting an error regarding implementation of Database abstract class.Please help me!!

**Comment by ritesh-singh** [comment]
https://stackoverflow.com/questions/47274677/room-cannot-find-implementation

https://stackoverflow.com/questions/44417136/room-persistence-library-run-time-exception-when-calling-rooms-inmemorybuilder-m/44582509

Can you check here, if your issues falls in these categories.

**Comment by ritesh-singh** [comment]
Closing this issue, it can be solved by following one of the above solution.

**Comment by ameybhandarkar** [comment]
Nope. None of the above solutions worked for me.

**Comment by pierretsap** [comment]
I had the same issue. I finally resolved it by adding these lines in my graddle file : 

```
def room_version = "2.2.3" // be sure to have the latest version of room
implementation "androidx.room:room-runtime:$room_version"
annotationProcessor "android.arch.persistence.room:compiler:$room_version"
```

**Comment by duttabhishek0** [comment]
Adding to @pierretsap if you are not using `androidx`, then adding the following would help:
```gradle
 // ViewModel and Live Data
 implementation "android.arch.lifecycle:extensions:1.1.1"
 kapt "android.arch.lifecycle:compiler:1.1.1"

 // Room
 implementation "android.arch.persistence.room:runtime:1.1.1"
 kapt "android.arch.persistence.room:compiler:1.1.1
```

Also do add `apply plugin  'kotlin-kapt'` in your  app's `build.gradle`

**Comment by AungHtetKyawWho** [comment]
yes. Thanks a bunch

**Comment by dhiru909** [comment]
but i am getting error please help

**Comment by abusaeed2433** [comment]
For those, who are still facing this issue, do these:

1. In your project level `build.gradle` file, add this:
```
plugins {
    id("com.google.devtools.ksp") version "2.1.20-1.0.31" apply false
}
```

2. In the module level `build.gradle` file, do these:
```
plugins {
    id("com.google.devtools.ksp")
}
// ...
dependencies {
    ksp("androidx.room:room-compiler:2.8.1")
}
```

Make sure to remove `kapt` and `annotationProcessor` room dependencies(if any).
